name: flutter_gemini_ai_chatbot
description: "Ai chatbot Using Gemini api"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.3
  image_picker: ^1.1.1
  dash_chat_2: ^0.0.20


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - asset/
